### ISSUE TITLE
How can I use this without outputting the image styles?

### ISSUE THREAD

**Issue by JacobDB** [drublic/gulp-css-background-remove#3]
I'd like to simply use this to remove the URLs from my "critical.css" file, as I then load in the URLs manually later. How can I prevent this from outputting the image.css file?

**Comment by thiagorb** [comment]
You can use the parameter writeImagesFile:
`cssBackgroundRemove({ 
    writeImagesFile: false
  })`

**Comment by JacobDB** [comment]
Ah! Thank you very much!
